package analysis.dataflow.flowsensitizer;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import util.OrderedPair;

public class SensitizerFact {
    private final Map<Integer, Set<Integer>> m;
    private final Set<Integer> escaped;

    public static SensitizerFact makeBottom() {
        return new SensitizerFact(new HashMap<Integer, Set<Integer>>(), new HashSet<Integer>());
    }

    private SensitizerFact(Map<Integer, Set<Integer>> m, Set<Integer> escaped) {
        this.m = m;
        this.escaped = escaped;
    }

    public SensitizerFact addToSetAt(int var, int sensitizer) {
        Map<Integer, Set<Integer>> m = deepCopyMap(this.m);

        if (m.containsKey(var)) {
            m.get(var).add(sensitizer);
        }
        else {
            Set<Integer> s = new HashSet<>();
            s.add(sensitizer);
            m.put(var, s);
        }

        return new SensitizerFact(m, this.escaped);
    }

    public SensitizerFact replaceSetAt(int var, Set<Integer> s) {
        Map<Integer, Set<Integer>> m = deepCopyMap(this.m);

        m.put(var, s);

        return new SensitizerFact(m, this.escaped);
    }

    public SensitizerFact replaceSetsAt(Set<OrderedPair<Integer, Set<Integer>>> updates) {
        Map<Integer, Set<Integer>> m = deepCopyMap(this.m);

        for (OrderedPair<Integer, Set<Integer>> update : updates) {
            Integer key = update.fst();
            Set<Integer> s = update.snd();
            m.put(key, s);
        }

        return new SensitizerFact(m, this.escaped);
    }

    public SensitizerFact addEscapee(int var) {
        Set<Integer> escaped = new HashSet<>(this.escaped);
        escaped.add(var);
        return new SensitizerFact(m, escaped);
    }

    public boolean isEscaped(int var) {
        return escaped.contains(var);
    }

    public SensitizerFact join(SensitizerFact that) {
        Map<Integer, Set<Integer>> m = deepCopyMap(this.m);

        for (Entry<Integer, Set<Integer>> kv : that.m.entrySet()) {
            Integer var = kv.getKey();
            Set<Integer> s = kv.getValue();

            if (m.containsKey(var)) {
                m.get(var).addAll(s);
            }
            else {
                m.put(var, s);
            }
        }

        return new SensitizerFact(m, this.escaped);
    }

    public Map<Integer, Set<Integer>> getMap() {
        return this.m;
    }

    private static Map<Integer, Set<Integer>> deepCopyMap(Map<Integer, Set<Integer>> m) {
        Map<Integer, Set<Integer>> m2 = new HashMap<>();

        for (Entry<Integer, Set<Integer>> kv : m.entrySet()) {
            Integer var = kv.getKey();
            Set<Integer> s = kv.getValue();

            Set<Integer> s2 = new HashSet<>(s);
            m2.put(var, s2);
        }

        return m2;
    }

    public static SensitizerFact joinCollection(Collection<SensitizerFact> c) {
        if (c.size() == 0) {
            return SensitizerFact.makeBottom();
        }
        else if (c.size() == 1) {
            return c.iterator().next();
        }
        else {
            Iterator<SensitizerFact> it = c.iterator();
            SensitizerFact f = it.next();

            while (it.hasNext()) {
                // XXX: this could be made more efficient
                f = f.join(it.next());
            }

            return f;
        }
    }

    /*
     * AUTOGENERATED STUFF
     *
     * Be sure to regenerate these (using Eclipse) if you change the number of fields in this class
     *
     * DEFINTIELY DONT CHANGE ANYTHING
     */

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((m == null) ? 0 : m.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof SensitizerFact)) {
            return false;
        }
        SensitizerFact other = (SensitizerFact) obj;
        if (m == null) {
            if (other.m != null) {
                return false;
            }
        }
        else if (!m.equals(other.m)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "(SensitizerFact " + m + ")";
    }

}
