package analysis.pointer.registrar.strings;

import java.util.Collections;
import java.util.Set;

import analysis.StringAndReflectiveUtil;
import analysis.pointer.graph.strings.StringLikeLocationReplica;
import analysis.pointer.graph.strings.StringLocationReplica;

import com.ibm.wala.classLoader.IField;
import com.ibm.wala.ipa.callgraph.Context;
import com.ibm.wala.types.TypeReference;

public class FieldStringVariable implements StringLikeVariable {

    private final IField f;
    private final TypeReference type;

    /* Factory Methods */

    public static FieldStringVariable makeString(IField f) {
        return new FieldStringVariable(f, StringAndReflectiveUtil.JavaLangStringTypeReference);
    }

    public static StringLikeVariable makeObject(IField f) {
        return new FieldStringVariable(f, StringAndReflectiveUtil.JavaLangObjectTypeReference);
    }

    /* Constructors */

    private FieldStringVariable(IField f, TypeReference type) {
        this.f = f;
        this.type = type;
    }

    /* Logic */

    @Override
    public Set<StringLikeLocationReplica> getStringLocationReplicas(Context context) {
        return Collections.<StringLikeLocationReplica> singleton(StringLocationReplica.make(context, this));
    }

    @Override
    public TypeReference getExpectedType() {
        return type;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }

    @Override
    public boolean isStringBuilder() {
        return false;
    }

    @Override
    public boolean isString() {
        return true;
    }

    @Override
    public boolean isNull() {
        return false;
    }

    /*
     * AUTOGENERATED STUFF
     *
     * Be sure to regenerate these (using Eclipse) if you change the number of fields in this class
     *
     * DEFINTIELY DONT CHANGE ANYTHING
     */

    @Override
    public String toString() {
        return "FieldStringVariable [f=" + f + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((f == null) ? 0 : f.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof FieldStringVariable)) {
            return false;
        }
        FieldStringVariable other = (FieldStringVariable) obj;
        if (f == null) {
            if (other.f != null) {
                return false;
            }
        }
        else if (!f.equals(other.f)) {
            return false;
        }
        return true;
    }

}
