package util.optional;

public final class NoneOptional<T> extends Optional<T> {

    @Override
    public boolean isNone() {
        return true;
    }

    @Override
    public T get() {
        throw new RuntimeException("No value in None case");
    }

    /*
     * AUTOGENERATED STUFF
     *
     * Be sure to regenerate these (using Eclipse) if you change the number of fields in this class
     *
     * DEFINTIELY DONT CHANGE ANYTHING
     */

    @Override
    public int hashCode() {
        return 31;
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof NoneOptional;
    }

    @Override
    public String toString() {
        return "NoneOptional []";
    }

}
