
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 10 19:10:33 EDT 2014
//----------------------------------------------------

package analysis.pointer.analyses.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CS = 4;
  public static final int SCS = 3;
  public static final int INT_LITERAL = 12;
  public static final int LPAR = 8;
  public static final int EOF = 0;
  public static final int FULL = 5;
  public static final int TYPE = 2;
  public static final int RBRACK = 11;
  public static final int DOT = 6;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int IDENTIFIER = 13;
  public static final int LBRACK = 10;
  public static final int RPAR = 9;
}

